### ISSUE TITLE
migrate报错

### ISSUE THREAD

**Issue by wxip** [mss-boot-io/mss-boot-admin#100]
mss-boot-admin: v0.4.1
首次执行migrate报错
![image](https://github.com/mss-boot-io/mss-boot-admin/assets/25923931/8d4f48ce-db58-4852-a314-533bcdd77051)
数据库没有生成tenant表
![image](https://github.com/mss-boot-io/mss-boot-admin/assets/25923931/e5aa4c1a-515a-46f3-b898-491754aa7825)

**Comment by lwnmengjing** [comment]
done
