### ISSUE TITLE
租户新增/编辑时间格式报错

### ISSUE THREAD

**Issue by ywstcc** [mss-boot-io/mss-boot-admin#103]
提交数据payload
```json
{
  "name": "mss-boot-io",
  "status": "enabled",
  "domains": [
    {
      "id": "9ea7a77ebd5b4595bf903398602a654a",
      "createdAt": "2024-06-24T09:38:27.33+08:00",
      "updatedAt": "2024-06-24T09:38:27.33+08:00",
      "tenantId": "88af0c4fb83c437986a094f13c0a8655",
      "name": "local",
      "domain": "localhost:8000"
    }
  ],
  "expire": "2124-05-30 09:38:27",
  "remark": "mss-boot-io"
}
```

返回msg：
```json
{
  "status": "error",
  "code": 422,
  "errorMessage": "parsing time \"2124-05-30 09:38:27\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \" 09:38:27\" as \"T\"",
  "traceId": "212f3a1b-e0fb-4798-b590-80b2581945ce"
}
```

**Comment by lwnmengjing** [comment]
使用接口请求的，还是在ui界面请求的

**Comment by ywstcc** [comment]
> 使用接口请求的，还是在ui界面请求的

在前端UI页面上操作的

**Comment by lwnmengjing** [comment]
> > 使用接口请求的，还是在ui界面请求的
> 
> 在前端UI页面上操作的

好的，了解，稍后会修复下

**Comment by mss-boot** [comment]
> 提交数据payload
> 
> ```json
> {
>   "name": "mss-boot-io",
>   "status": "enabled",
>   "domains": [
>     {
>       "id": "9ea7a77ebd5b4595bf903398602a654a",
>       "createdAt": "2024-06-24T09:38:27.33+08:00",
>       "updatedAt": "2024-06-24T09:38:27.33+08:00",
>       "tenantId": "88af0c4fb83c437986a094f13c0a8655",
>       "name": "local",
>       "domain": "localhost:8000"
>     }
>   ],
>   "expire": "2124-05-30 09:38:27",
>   "remark": "mss-boot-io"
> }
> ```
> 
> 返回msg：
> 
> ```json
> {
>   "status": "error",
>   "code": 422,
>   "errorMessage": "parsing time \"2124-05-30 09:38:27\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \" 09:38:27\" as \"T\"",
>   "traceId": "212f3a1b-e0fb-4798-b590-80b2581945ce"
> }
> ```

修复代码已经提交到main分支，请分别更新前后端main分支

**Comment by lwnmengjing** [comment]
done
